version: "3"

services: 
  app: 
    build: . 
    container_name: easy_app
    command: npm start 
    ports:
      - "3000:3000" 
    volumes:
      - .:/usr/app ## monitoro a pasta atual . e envio as alterações para /usr/app
  mongo:
    image: mongo
    container_name: easy_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  mongo-express:
    image: mongo-express
    container_name: easy_express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin